## Standard Settings
Company:
  - Name: TechBash Foundation
Layout: /_layout.cshtml

## Computed Settings
Copyright: | 
  => { 
    string company = Context.GetString("Company.Name")
    return $"Copyright ©{DateTime.Now.Year} {company}" 
  }