## Standard Settings
Company:
  Name: TechBash Foundation
Layout: /_layout.cshtml

## Computed Settings
Copyright: | 
  => { 
    foreach (string i in Context.Keys) {
      Console.WriteLine(i);
    }
    string company = Context.GetString("Company:Name");
    return $"Copyright ©{DateTime.Now.Year} {company}";
  }